name: Build and Release Anime Player

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        os: [win, linux]

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: npm install

      - name: Build for ${{ matrix.os }}
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          if [ "${{ matrix.os }}" == "win" ]; then
            npm run dist -- --win
          elif [ "${{ matrix.os }}" == "linux" ]; then
            npm run dist -- --linux
          fi

      - name: Upload Artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Anime-Player-${{ matrix.os }}-${{ github.sha }}
          path: dist/*
